# Generated by Django 5.2.4 on 2025-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_familylink_patientconnectcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
