# Generated by Django 5.2.4 on 2025-09-27 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_memory_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familylink',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='memory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='familylink',
            constraint=models.UniqueConstraint(fields=('patient', 'family_member'), name='unique_family_link'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_family_member_per_user'),
        ),
    ]
