# Generated by Django 5.2.4 on 2025-09-27 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_familylink_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['memory', '-created_at'], name='api_memoryc_memory__1da151_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='memory_images/')),
                ('image_url', models.URLField(blank=True, max_length=600, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.memory')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['memory', 'order'], name='api_memoryi_memory__e1852f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['memory', 'created_at'], name='api_memoryl_memory__036be6_idx')],
                'unique_together': {('memory', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MemoryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_people', to='api.memory')),
            ],
            options={
                'indexes': [models.Index(fields=['memory', 'name'], name='api_memoryp_memory__74ef44_idx')],
                'unique_together': {('memory', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MemoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#999999', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tags', to='api.memory')),
            ],
            options={
                'indexes': [models.Index(fields=['memory', 'tag_name'], name='api_memoryt_memory__960db6_idx')],
                'unique_together': {('memory', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='MemoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='memory_videos/')),
                ('video_url', models.URLField(blank=True, max_length=600, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=600, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.memory')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['memory', 'order'], name='api_memoryv_memory__eae46b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryVoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='memory_audio/')),
                ('audio_url', models.URLField(blank=True, max_length=600, null=True)),
                ('speaker_name', models.CharField(blank=True, max_length=100)),
                ('speaker_relation', models.CharField(blank=True, max_length=100)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('waveform_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='api.memory')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['memory', 'created_at'], name='api_memoryv_memory__d0045b_idx'), models.Index(fields=['speaker_name'], name='api_memoryv_speaker_122ce6_idx')],
            },
        ),
    ]
